name: Build and Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: macos-11

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: npm ci

      - name: Unit Tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: distribution
          path: ./dist

  dev_delpoy:
    name: Dev Deploy
    needs: build
    runs-on: macos-11
    environment:
      name: dev
      url: https://virtual-hub-dev.netlify.app

    steps:
      - name: Download Latest Artifact
        uses: actions/download-artifact@v3
        with:
          name: distribution
          path: dist

      - name: Deploy to Netlify Dev
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "./dist"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "${{ github.event.workflow_run.head_sha }} ${{ github.event.head_commit.message }}"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

  prod_delpoy:
    name: Prod Deploy
    needs: dev_delpoy
    runs-on: macos-11
    environment:
      name: production
      url: https://virtual-hub.netlify.app

    steps:
      - name: Download Latest Artifact
        uses: actions/download-artifact@v3
        with:
          name: distribution
          path: dist

      - name: Deploy to Netlify Prod
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "./dist"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "${{ github.event.workflow_run.head_sha }} ${{ github.event.head_commit.message }}"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
